# Dictionary with words and hints for Hangman to be imported

words = [

    {"word": "spring", "hint": "season (6 Letters)"},
    {"word": "summer", "hint": "season (6 Letters)"},
    {"word": "autumn", "hint": "season (6 Letters)"},
    {"word": "winter", "hint": "season (6 Letters)"},
    {"word": "strawberry", "hint": "fruit (10 Letters)"},
    {"word": "orange", "hint": "fruit (6 Letters)"},
    {"word": "peach", "hint": "fruit (5 Letters)"},
    {"word": "cherry", "hint": "fruit (6 Letters)"},
    {"word": "pear", "hint": "fruit (4 Letters)"},
    {"word": "lychee", "hint": "fruit (6 Letters)"},
    {"word": "kiwi", "hint": "fruit (4 Letters)"},
    {"word": "cat", "hint": "animal (3 Letters)"},
    {"word": "dog", "hint": "animal (3 Letters)"},
    {"word": "rabbit", "hint": "animal (6 Letters)"},
    {"word": "horse", "hint": "animal (5 Letters)"},
    {"word": "hedgehog", "hint": "animal (8 Letters)"},
    {"word": "mouse", "hint": "animal (5 Letters)"},
    {"word": "car", "hint": "transport (3 Letters)"},
    {"word": "boat", "hint": "transport (4 Letters)"},
    {"word": "train", "hint": "transport (5 Letters)"},
    {"word": "plane", "hint": "transport (5 Letters)"},
    {"word": "motorbike", "hint": "transport (9 Letters)"},
    {"word": "carrot", "hint": "vegetable (6 Letters)"},
    {"word": "corn", "hint": "vegetable (4 Letters)"},
    {"word": "cucumber", "hint": "vegetable (8 Letters)"},
    {"word": "onion", "hint": "vegetable (5 Letters)"},
    {"word": "beetroot", "hint": "vegetable (8 Letters)"},
    {"word": "potato", "hint": "vegetable (6 Letters)"},
    {"word": "happy", "hint": "emotion (5 Letters)"},
    {"word": "sad", "hint": "emotion (3 Letters)"},
    {"word": "angry", "hint": "emotion (5 Letters)"},
    {"word": "bored", "hint": "emotion (5 Letters)"},
    {"word": "surprised", "hint": "emotion (9 Letters)"},
    {"word": "excited", "hint": "emotion (7 Letters)"},
]
