# Dictionary with words and hints for Hangman to be imported

words = [

    {"word": "spring", "hint": "season"},
    {"word": "summer", "hint": "season"},	
    {"word": "autumn", "hint": "season"},
    {"word": "winter", "hint": "season"},
    {"word": "strawberry", "hint": "fruit"},
    {"word": "orange", "hint": "fruit"},
    {"word": "peach", "hint": "fruit"},
    {"word": "cherry", "hint": "fruit"},
    {"word": "pear", "hint": "fruit"},
    {"word": "lychee", "hint": "fruit"},
    {"word": "kiwi", "hint": "fruit"},
    {"word": "cat", "hint": "animal"},
    {"word": "dog", "hint": "animal"},
    {"word": "rabbit", "hint": "animal"},
    {"word": "horse", "hint": "animal"},
    {"word": "hedgehog", "hint": "animal"},
    {"word": "mouse", "hint": "animal"},
    {"word": "car", "hint": "transport"},
    {"word": "boat", "hint": "transport"},
    {"word": "train", "hint": "transport"},
    {"word": "plane", "hint": "transport"},
    {"word": "motorbike", "hint": "transport"},
    {"word": "carrot", "hint": "vegetable"},
    {"word": "corn", "hint": "vegetable"},
    {"word": "cucumber", "hint": "vegetable"},
    {"word": "onion", "hint": "vegetable"},
    {"word": "beetroot", "hint": "vegetable"},
    {"word": "potato", "hint": "vegetable"},
    {"word": "happy", "hint": "emotion"},
    {"word": "sad", "hint": "emotion"},
    {"word": "angry", "hint": "emotion"},
    {"word": "bored", "hint": "emotion"},
    {"word": "surprised", "hint": "emotion"},
    {"word": "excited", "hint": "emotion"},
    
]
